Tic-tac-toe

Let's try to use MVC.

In [1]:
import numpy as np

#Set up a game class.
class GameModel(object):
    def __init__(self):
        #The state consists of board, turn, and outcome, and whether the game is ongoing.
        #Th board is 3 by 3. Board positions are listed horizontally.
        #0 is empty, 1 is "X", and 2 is "O".
        self.board = np.array([0]*9)
        self.outcome = 0 #ongoing
        self.turn = "X"
        
    def get_board(self):
        return self.board
    
    def _set_board(self, new_board):
        self.board = new_board
    
    def _check_board(self):
        #Implement later.
        #All valid values, maximum one winner.
        return True
    
#     def _update_state(self):
#         #Updates the state, given the board, turn, and outcome.
#         #board_X = np.where((self.board == 1),1,0)
#         boolArr = (self.board == 1)
#         board_X = np.where(boolArr,np.ones_like(self.board),np.zeros_like(self.board))
#         #board_O = (self.board = 2)
#         print(boolArr)
#         print(board_X)
#         return True
              
    
    def get_turn(self):
        return self.turn
    
    def _set_turn(self, new_turn):
        self.turn = new_turn
    
    def _change_turn(self):
        if self.turn == "X":
            self._set_turn("O")
        else:
            self._set_turn("X")
            
    def get_outcome(self):
        return self.outcome
    
    def _update_outcome(self):
        if self.outcome != 0:
            raise error
        
        #Horiz player 1
        for i in range(2):
            if (self.board[3*i] == 1 and self.board[1+3*i] == 1 and self.board[2+3*i] == 1):
                self.outcome = 1 #First Player won.
        #Vert player 1
        for i in range(2):
            if (self.board[i] == 1 and self.board[3+i] == 1 and self.board[6+i] == 1):
                self.outcome = 1 #First Player won.
        
        #Diag player 1
        if (self.board[0] == 1 and self.board[4] == 1 and self.board[8] == 1):
                self.outcome = 1
        
        if (self.board[2] == 1 and self.board[4] == 1 and self.board[6] == 1):
                self.outcome = 1
        
        
        #Horiz player 2
        for i in range(2):
            if (self.board[3*i] == 2 and self.board[1+3*i] == 2 and self.board[2+3*i] == 2):
                self.outcome = 2 #First Player won.
        #Vert player 2
        for i in range(2):
            if (self.board[i] == 2 and self.board[3+i] == 2 and self.board[6+i] == 2):
                self.outcome = 2 #First Player won.
        
        #Diag player 2
        if (self.board[0] == 2 and self.board[4] == 2 and self.board[8] == 2):
                self.outcome = 2
        
        if (self.board[2] == 2 and self.board[4] == 2 and self.board[6] == 2):
                self.outcome = 2
        
        if self.outcome not in (1,2):
            if 0 not in self.board:
                self.outcome = 3
                
    
    
    def check_move_valid(self, move):
        if move[0] not in ('X','O') or move[1] not in range(0,9):
            return False
        if self.get_board()[move[1]] != 0:
            return False
        return True
    
    def implement_move(self, move):
        #If valid, do and return true. else return false.
        #move is a pair consisting of player and square. Square is from 0 to 8.
        old_board = self.get_board()
        if self.check_move_valid(move):
            if move[0] == "X":
                new_board = old_board
                new_board[move[1]] = 1
                self._set_board(new_board)
            if move[0] == "O":
                new_board = old_board
                new_board[move[1]] = 2
                self._set_board(new_board)
            self._update_outcome()
#             self._update_state()
            if self.outcome == 0:
                self._change_turn()
            return True
        else:
            return False
        
    def get_valid_moves(self):
        #Returns the set of valid moves. These are squares, 1 to 9.
        valid_moves = []
        turn = self.get_turn()
        for square in range(0,9):
            candidate_move = tuple([turn, square])
            if self.check_move_valid(candidate_move):
                valid_moves.append(square+1)
        valid_moves = np.asarray(valid_moves)
        return(valid_moves)
        
        
        
class GameASCIIView(object):
    #Displays info to the user.
    def __init__(self, gameModel, controller = None):
        self.gameModel = gameModel
#         self.controller = controller
    
    def display_board(self):
        #Assumes correct input.
        board = self.gameModel.get_board()
        display_board=[' ']*9
        for i in range(9):
            if board[i] == 1:
                display_board[i] = "X"
            if board[i] == 2:
                display_board[i] = "O"
        print(display_board[0] + '|' + display_board[1] + '|' + display_board[2])
        print('-'*5)
        print(display_board[3] + '|' + display_board[4] + '|' + display_board[5])
        print('-'*5)
        print(display_board[6] + '|' + display_board[7] + '|' + display_board[8])
    
    def display_turn(self):
        turn = self.gameModel.get_turn()
        if turn == "X":
            print("It's X's turn.")
        if turn == "O":
            print("It's O's turn.")
    
    def display_outcome(self):
        outcome = self.gameModel.get_outcome()
        if outcome == 0:
            print("The game is ongoing.")
        if outcome == 1:
            print("Player X won.")
        if outcome == 2:
            print("Player O won.")
        if outcome == 3:
            print("The game was a draw.")
    
    def display_valid_moves(self):
        moves = self.gameModel.get_valid_moves()
#         print(type(moves))
        print(moves)
        
    def display(self):
        self.display_board()
        self.display_turn()
        self.display_outcome()
    
#     def display_state(self):
#         print(self.gameModel.state)
        
    def request_move(self):
        print("Please")
        
class GameController(object):
    def __init__(self, gameModel):
        self.gameModel = gameModel
        self.view = GameASCIIView(gameModel, self)
        
    def get_move(self):
        while True:
            square_in = input('Enter square: ')
            if square_in not in ('1','2','3','4','5','6','7','8','9'):
                print("Not an appropriate choice.")
            else:
                square = int(square_in) - 1
                move = [self.gameModel.get_turn(),square]
                if self.gameModel.check_move_valid(move):
                    break
                else:
                    print("Not a valid move.")
        self.gameModel.implement_move(move)
        
    def run_game(self):
        while self.gameModel.outcome == 0:
            self.view.display()
            self.view.display_valid_moves()
            self.get_move()
        self.view.display_board()
        self.view.display_outcome()
     

    
    
    

# my_game_view = GameView(my_game)
# my_game_view.display_board()
# print(my_game.get_board())
# my_game._update_outcome()
# print(my_game.get_outcome())
# my_game._set_board([0]+[1,0,0]*3 + [0]*9)
# my_game_view.display_board()
# print(my_game.get_board())
# print(my_game.get_outcome())
# my_game._update_outcome()
# print(my_game.get_outcome())

#my_game.outcome = 0
#my_game.reset_board()




In [2]:

my_game = GameModel()
my_game_controller = GameController(my_game)

my_game._set_board([1,2,1,0,2,0,0,0,0])
#my_game_controller.view.display_board()
#my_game_controller.view.display_state()
# my_game._update_state()

In [3]:
my_game = GameModel()
my_game_controller = GameController(my_game)

my_game_controller.run_game()

 | | 
-----
 | | 
-----
 | | 
It's X's turn.
The game is ongoing.
[1 2 3 4 5 6 7 8 9]
Enter square: 3
 | |X
-----
 | | 
-----
 | | 
It's O's turn.
The game is ongoing.
[1 2 4 5 6 7 8 9]
Enter square: 4
 | |X
-----
O| | 
-----
 | | 
It's X's turn.
The game is ongoing.
[1 2 5 6 7 8 9]
Enter square: 2
 |X|X
-----
O| | 
-----
 | | 
It's O's turn.
The game is ongoing.
[1 5 6 7 8 9]
Enter square: 1
O|X|X
-----
O| | 
-----
 | | 
It's X's turn.
The game is ongoing.
[5 6 7 8 9]
Enter square: 7
O|X|X
-----
O| | 
-----
X| | 
It's O's turn.
The game is ongoing.
[5 6 8 9]
Enter square: 5
O|X|X
-----
O|O| 
-----
X| | 
It's X's turn.
The game is ongoing.
[6 8 9]
Enter square: 9
O|X|X
-----
O|O| 
-----
X| |X
It's O's turn.
The game is ongoing.
[6 8]
Enter square: 6
O|X|X
-----
O|O|O
-----
X| |X
Player O won.
